[package]
name = "slab-iter"
version = "0.1.0"
authors = ["frozenlib"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/frozenlib/slab-iter"
documentation = "https://docs.rs/slab-iter/"
keywords = ["slab", "allocator", "map", "vec"]
categories = ["data-structures", "memory-management"]
description = "Slab allocator for fast iterating by optimizing the free space."
edition = "2018"

[dependencies]

[dev-dependencies]
proptest = "0.10"
criterion = "0.3"
slab = "0.4"

[lib]
bench = false

[[bench]]
name = "benchmarks"
harness = false