[package]
name = "slabmap"
version = "0.1.1"
authors = ["frozenlib"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/frozenlib/slabmap"
documentation = "https://docs.rs/slabmap/"
keywords = ["slab", "allocator", "map", "vec"]
categories = ["data-structures", "memory-management"]
description = "HashMap-like collection that automatically determines the key."
edition = "2018"

[dependencies]

[dev-dependencies]
proptest = "0.10"
criterion = "0.3.4"
slab = "0.4"
rand = "0.7"
tinytemplate = "1.2.1" # Because criterion depends on a version of atty that cannot be compiled.
atty = "0.2.14" # Because criterion depends on a version of atty that cannot be compiled.

[lib]
bench = false

[[bench]]
name = "regression"
harness = false

[[bench]]
name = "compare"
harness = false
