[package]
name = "slab-map"
version = "0.1.0"
authors = ["frozenlib"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/frozenlib/slab-map"
documentation = "https://docs.rs/slab-map/"
keywords = ["slab", "allocator", "map", "vec"]
categories = ["data-structures", "memory-management"]
description = "HashMap-like collection that automatically determines the key."
edition = "2018"

[dependencies]

[dev-dependencies]
proptest = "0.10"
criterion = "0.3"
slab = "0.4"
rand = "0.7"

[lib]
bench = false

[[bench]]
name = "regression"
harness = false

[[bench]]
name = "compare"
harness = false
